name = "SchwartzSmith"
uuid = "51ce3320-fff1-11e9-01e9-5d44285ae9aa"
authors = ["marinadietze <marinadietzem@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
